# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeter', '0002_auto_20160711_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expires_timestamp',
            field=models.DateTimeField(default=datetime.date(2016, 7, 12)),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
