# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20160713_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 7, 13, 5, 14, 42, 76292, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greeting',
            name='doctor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
