# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20160713_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
