# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_greeting_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
